billing_system2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'index/', include('bills.urls'))
]

bills/urls.py
from django.conf.urls import url
from . import views

app_name = 'bill'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^bill/',views.cal_amount,name='cal_amount'),
    url(r'^test/$',views.test_iterations,name='test_iterations')
]

bills/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.utils import timezone
# Create your models here.

@python_2_unicode_compatible
class Customer(models.Model):
    customer_id = models.AutoField(primary_key=True,default="1")
    customer_name = models.CharField(max_length=200,default="")
    customer_mob_no = models.CharField(max_length=200,default="")
    customer_email =  models.EmailField(max_length=200,default="")

    def __str__(self):
        return self.customer_name

@python_2_unicode_compatible
class Product(models.Model):
	product_id = models.AutoField(primary_key=True)
	product_name = models.CharField(max_length=200)
	product_detail = models.CharField(max_length=200)
	product_price = models.IntegerField(default=0)
	
	def __str__(self):
		return self.product_name

@python_2_unicode_compatible
class Cust_bill(models.Model):
	customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
	shop_name = "APNI_DUKAAN"
	purchase_date = models.DateTimeField('purchased date')
	total_items = models.IntegerField(default=0)
	amount = models.IntegerField(default=0)
	
	def __str__(self):
		return self.amount


@python_2_unicode_compatible
class Inventory(models.Model):
	product = models.OneToOneField('Product', on_delete=models.CASCADE)
	item_present = models.IntegerField(default=0)
	
	def __str__(self):
		return str(self.item_present)

bills/forms.py
from django import forms
from django.contrib.auth import get_user_model

class InfoForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
			attrs={"class":"form-control",
			"placeholder":"Your Full Name"
			}
			))

    mobilenumber = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control",
               "placeholder": "Your Mobile Number"
               }
    ))

    email = forms.EmailField(widget=forms.EmailInput(
			attrs={"class":"form-control",
			"placeholder":"Your Email"
			}
			))

bills/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404
from .forms import InfoForm
from .models import Customer, Product, Cust_bill, Inventory


# Create your views here.

def index(request):
    form = InfoForm(request.POST or None)

    username = request.POST.get('username')
    mobilenumber = request.POST.get('mobilenumber')
    email = request.POST.get('email')
    # username = form.cleaned_data.get("username")
    # mobilenumber = form.cleaned_data.get("mobilenumber")
    # email = form.cleaned_data.get("email")
    if form.is_valid():
        cus = Customer(customer_name=username,customer_mob_no=mobilenumber,customer_email=email)
        cus.save()
        print(form.cleaned_data)
    product = Product.objects.all()
    product_no = Product.objects.all().count()     
    print ("count: %d"% product_no)
    inventory = Inventory.objects.all()
    mylist = []
    # db store
    context = {
        'title': 'Myrel Billing System',
        'Name': username,
        'mobilenumber': mobilenumber,
        'products':product,
        'inventory':inventory,
        'product_no':product_no,
        'mylist':mylist
    }
    #print product

    # for p in product.product_set.all:
    #     print p.product.name

    if request.method == "POST" and username != None:
        return render(request, "bills/menu.html", context)

    return render(request, "bills/index.html", {'form': form, 'title': 'Billing System'})


def cal_amount(request):
    print("cal_amount")
    amount = 0
    count = 0

    username = request.POST.get('username')
    mobilenumber = request.POST.get('mobilenumber')

    products = Product.objects.all()
    total_count = Product.objects.all().count()
    for p in products:
        id = p.product_id
        q = request.POST.get('q_id_' + str(id))
        if q is not None and q != '' and int(q):
            q = int(q)
            amount += q * int(p.product_price)
            count += 1

    context = {
        'count': count,
        'amount': amount
    }
    # cus_name = request.POST.get('name')
    # x = request.POST.get('')
    # quantity2 = request.POST.get('quantity2')
    return render(request, "bills/bills.html", context)


def test_iterations(request):
    data = {
        "products":
            [


                     {
                         "name": "Aloo",
                           "price": 30
                      },


                        {
                            "name": "Gobhi",
                            "price": 40
                        }

            ]
    }

    return render(request=request, template_name="bills/test_iterations.html", context=data)

bills/templates/bills/bills.html
TOTAL ITEMS {{ count }}<br>
TOTAL AMOUNT {{ amount }}<br>
<br>
Thank You

bills/templates/bills/index.html
<!doctype html>
	<html lang="en">
	  <head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

	    <title>Billing System</title>
	  </head>
	  <body>
      <center><h1>{{ title }}</h1></center>
	  <div class='container'>
	  	<div class='row'>
	  		<div class='col'>
	  			<div class='col-sm-6 col-sm-12'>
	 				<form method='POST'>
	 					{% csrf_token %}
	 					{{ form }}
	 					<br><button type="submit" class="btn btn-primary">Submit</button>
	  				</form>
	  			</div>
	  		</div>
	  	</div>
	  </div>
	    <!-- Optional JavaScript -->
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
	  </body>
	</html>

bills/templates/bills/list.html
<form method='POST' action="{% url 'bill:db_entry' %}">
		{% csrf_token %}
    <input type="hidden" name="name" value="{{ Name }}">
	<input type="hidden" name="mobilenumber" value="{{ mobilenumber }}">
    <table>
        <tr>
            <th>Items-Name</th>&nbsp
            <th><center>Quantity</center></th>&nbsp
            <th><center>Price[Per_units]</center></th>
        </tr>
        {% for p in products %}
            <tr>
            <td>{{ p.product_name }}</td>&nbsp
            <td><input type="number" min="0" name="{% {} %}" value="0"></td>&nbsp
            <td><center>{{ p.product_price }}</center></td>
            </tr>
        {% endfor %}                            
    </table>
		<br><button type="submit" class="btn btn-primary">Submit</button>
</form>

bills/templates/bills/menu.html
{% load keyy %}
<!doctype html>
	<html lang="en">
	  <head>
	    <!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

	    <title>Menu</title>
	  </head>
	  <body>
      <center><h1>{{ title }}</h1></center>
	  <center>
      <div class='container'>
	  	<div class='row'>
	  		<div class='col'>
	  			<div class='col-sm-6 col-sm-12'>
                    <h3>Menu Options</h3>
                    Name:{{ Name }}<br>
                    Mob.No:{{ mobilenumber }}

	 				<form method='POST' action="{% url 'bill:cal_amount' %}" name= 'myform'>
	 					{% csrf_token %}
                        <input type="hidden" name="name" value="{{ Name }}">
                        <input type="hidden" name="mobilenumber" value="{{ mobilenumber }}">
                        <table>
                            <tr>
                                <th>Items-Name</th>&nbsp
                                <th><center>Quantity</center></th>&nbsp
                                <th><center>Price[Per_units]</center></th>
                            </tr>
                            {{ product.count }}
                            {% for p in products %}
                                <tr>
                                <td>{{ p.product_name }}</td>&nbsp
                                <td><input type="number" min="0" name="q_id_{{ p.product_id }}"></td>&nbsp
                                <td><center>{{ p.product_price }}</center></td>
                                </tr>
                            {% endfor %}                            
                        </table>
	 					<br><button type="submit" class="btn btn-primary">Submit</button>
	  				</form>
	  			</div>
	  		</div>
	  	</div>
	  </div>
      </center>
	    <!-- Optional JavaScript -->
	    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
	  </body>
	  <script type="text/javascript">
	  	function submitform()
	  	{
	  	var formData = JSON.stringify($("#myform").serializeArray());
	  	console.log(formData)
	  	}
	  </script>
	</html>

bills/templates/bills/test_iterations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
</head>
<body>

{% if products %}
    <ul>
    {% for product in products %}
        <li>
            <p>{{ product.name }}</p>
            <p>{{ product.price }}</p>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No products are available.</p>
{% endif %}
</body>
</html>

bills/templates/bills/try.html
{% for p in products %}
<tr>
<td>{{ p.product_name }}</td>
<td><input type="number" min="0" name="quantity1" value="0"></td>
<td><center>{{ p.product_price }}</center></td>
</tr>
{% endfor %}


max="{{ inventory.item_present.filter(product.product_name == p.product_name)}}"



bills.html
<center><h1>Name:{{ name }}</h1>
<h2>Mob.No:{{ mobilenumber }}</h2>
<table>
{% if quatity1 %}
    <tr><td>Vanila:</td><td>{{ v_amount }}</td> <td>{{ quatity1 }}</td></tr>
{% endif %}
{% if quatity2 %}
    <tr><td>Butterscotch:</td><td>{{ b_amount }}</td> <td>{{ quatity2 }}</td></tr>
{% endif %}
{% if quatity3 %}
    <tr><td>Chocolate:</td><td>{{ c_amount }}</td> <td>{{ quatity3 }}</td></tr>
{% endif %}
{% if quatity4 %}
    <tr><td>Strawberry:</td><td>{{ s_amount }}</td> <td>{{ quatity4 }}</td></tr>
{% endif %}
{% if quatity5 %}
    <tr><td>Mango:</td><td>{{ m_amount }}</td> <td>{{ quatity5 }}</td></tr>
{% endif %}
<tr><td>Total</td><td colspan="2">{{ total }}</td></tr>
</table>
<button onclick="myFunction()">Print this page</button>
</center>
<script>
function myFunction() {
    window.print();
}
</script>